# Generated by Django 3.0.8 on 2020-07-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заведения')),
                ('photo', models.ImageField(blank=True, upload_to='places/', verbose_name='Фотография заведения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес заведения')),
                ('open', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Координаты (широта)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Координаты (долгота)')),
                ('average_cost', models.FloatField(blank=True, null=True, verbose_name='Средняя стоимость блюд')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведение',
                'ordering': ['id'],
            },
        ),
    ]
