# Generated by Django 3.0.8 on 2020-07-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ингредиента')),
                ('calories', models.IntegerField(verbose_name='Калорийность ингредиента (ккал)')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиент',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заведения')),
                ('photo', models.ImageField(blank=True, upload_to='places/', verbose_name='Фотография заведения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес заведения')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Координаты (широта)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Координаты (долгота)')),
                ('average_cost', models.FloatField(default=0, verbose_name='Средняя стоимость блюд')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведение',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('photo', models.ImageField(blank=True, upload_to='dishes/', verbose_name='Фотография блюда')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Суммарная калорийность (ккал)')),
                ('cost', models.FloatField(verbose_name='Стоимость блюда')),
                ('ingredients', models.ManyToManyField(to='eats.Ingredient', verbose_name='Ингредиенты')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eats.Place', verbose_name='Заведение блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
                'ordering': ['id'],
            },
        ),
    ]
